version: '3.7'

services:
  users_setter:
    image: imageget
    restart: always
    depends_on:
      - db
    ports:
      - "9000:8080"
    links:
      - db
  db:
    image: mongo
    container_name: "db"
    restart: always
    environment:
      port: "27017:27017"

  ansible-server:
    build: ../ansible/
    image: ansible
    container_name: ansible
    volumes:
      - ../ansible/:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ansible-project:/tmp
    command: ansible-playbook playbook.yml -i inventories/servers.yml
    networks:
      static-network:
        ipv4_address: 172.140.128.4
    restart: on-failure

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.140.0.0/16